# Do: pin all runtime dependencies in this spec with PEP 440 version specifiers
name: accessibility-check-backend-run-env
channels:
  - defaults
  - conda-forge
  - huggingface
  - anaconda
dependencies:
  - python~=3.8.6
  - pip~=20.2
  - pip:
      - fastapi
      - gunicorn
      - imutils
      - langid
      - lxml
      - opencv-python
      - python-multipart
      - selenium
      - uvicorn[standard]
      - sentence-transformers
      - cairosvg
