# Do not: include runtime dependencies in this spec
name: accessibility-check-backend-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python~=3.8.6
  - bump2version
  - coloredlogs
  - conda-merge
  - cruft
  - docutils
  - fastapi
  - hvplot
  - invoke
  - ipywidgets
  - jupyterlab
  - mamba
  - matplotlib
  - moto
  - nodejs
  - nomkl
  - mypy
  - pip
  - pre-commit
  - proselint
  - pydantic
  - pydocstyle
  - safety
  - selenium
  - shellcheck
  - snakeviz
  - tqdm
  - pip:
      - black
      - flake8
      - flake8-comprehensions
      - flake8-bandit
      - flake8-bugbear
      - flake8-isort
      - flake8-mutable
      - flake8-rst-docstrings
      - imutils
      - opencv-python
      - pathos
      - portray
      - pytest
      - pytest-bdd
      - pytest-clarity
      - pytest-cov
      - pytest-vcr
      - pytest-xdist
      - scalene
      - snoop
